
export const CREATE_TODOS_PENDING = 'CREATE_TODOS_PENDING';
export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';

export const GET_TODOS_PENDING = 'GET_TODOS_PENDING';
export const GET_TODOS = 'GET_TODOS';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';

export const GET_TODO = 'GET_TODO';
export const GET_TODO_ERROR = 'GET_TODO_ERROR';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';